name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 需要写权限来创建 Release

jobs:
  build:

    runs-on: windows-latest  # 使用 Windows 运行环境

    env:
      Nuitka_OPTIONS: "--lto=no --onefile --standalone --include-module=gradio,json,requests --include-package=PIL.ImageQt --output-filename=app.exe app.py --assume-yes-for-downloads --show-progress --jobs=3"
      RELEASE_TAG: "v1.0.1"  # 手动填写的版本号

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
    - name: Verify Nuitka installation
      run: |
        where nuitka
        nuitka --version
    - name: Build EXE with Nuitka
      run: |
        nuitka ${{ env.Nuitka_OPTIONS }}
    - name: Check if app.exe exists
      run: |
        if (-Not (Test-Path -Path ".\app.exe")) {
          throw "app.exe was not generated successfully."
        }
    - name: Zip the output
      run: |
        Compress-Archive -Path .\app.exe -DestinationPath .\app.zip
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        token: ${{ secrets.ACTION_TOKEN }}
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: app.zip
        asset_content_type: application/zip
    - name: Post job cleanup
      run: |
        git config --global --unset-all safe.directory
        git config --local --unset-all core.sshCommand
        git config --local --unset-all http.https://github.com/.extraheader
        git submodule foreach --recursive "git config --local --unset-all core.sshCommand"
        git submodule foreach --recursive "git config --local --unset-all http.https://github.com/.extraheader"
