name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:

    runs-on: windows-latest

    env:
      Nuitka_OPTIONS: "--onefile --standalone --include-module=gradio,json,requests --include-package=PIL.ImageQt --output-filename=app.exe app.py --assume-yes-for-downloads --show-progress --jobs=3"
      APP_BRANCH: "app"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
    - name: 构建
      run: |
        ping 127.0.0.1
    - name: 重命名
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
        $newFileName = "$timestamp_FAID.py"
        $originalFilePath = "app.py"
        $newFilePath = Join-Path -Path "." -ChildPath $newFileName
        Move-Item -Path $originalFilePath -Destination $newFilePath
        Write-Output "File has been renamed to: $newFilePath"
    - name: 创建 apps 目录
      run: |
        mkdir -p apps
    - name: 移动文件到 apps 目录
      run: |
        mv $newFilePath apps/
    - name: 提交并推送更改
      env:
        ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout main || git checkout -b main
        git add apps/$newFileName
        git commit -m "Add new build: $newFileName" || echo "No changes to commit"
        git push https://$ACTION_TOKEN@github.com/${{ github.repository }}.git main
