name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 需要写权限来创建 Release

jobs:
  build:

    runs-on: windows-latest  # 使用 Windows 运行环境

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
    - name: Verify Nuitka installation
      run: |
        where nuitka
        nuitka --version
    - name: Build EXE with Nuitka
      run: |
        nuitka --standalone --onefile --enable-plugin=tk-inter --output-filename=app.exe app.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.exe
        asset_name: app.exe
        asset_content_type: application/octet-stream
