name: Python 应用程序构建与发布

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 需要写权限来创建 Release

jobs:
  构建与发布:

    runs-on: windows-latest  # 使用 Windows 运行环境

    env:
      Nuitka_OPTIONS: "--lto=no --onefile --standalone --include-module=gradio,json,requests --include-package=PIL.ImageQt --output-filename=app.exe app.py --assume-yes-for-downloads --show-progress --jobs=3"
      RELEASE_TAG: "v1.0.1"  # 手动填写的版本号

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    - name: 设置 Python 3.10 环境
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
    - name: 验证 Nuitka 安装
      run: |
        where nuitka
        nuitka --version
    - name: 使用 Nuitka 构建 EXE 文件
      run: |
        nuitka ${{ env.Nuitka_OPTIONS }}
    - name: 检查 app.exe 是否生成
      run: |
        if (-Not (Test-Path -Path ".\app.exe")) {
          throw "app.exe was not generated successfully."
        }
    - name: 压缩输出文件
      run: |
        Compress-Archive -Path .\app.exe -DestinationPath .\app.zip
    - name: 创建 Release
      id: 创建_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false
        token: ${{ secrets.ACTION_TOKEN }}
    - name: 上传 Release 资源
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.创建_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: app.zip
        asset_content_type: application/zip
    - name: 清理工作环境
      run: |
        git config --global --unset-all safe.directory
        git config --local --unset-all core.sshCommand
        git config --local --unset-all http.https://github.com/.extraheader
        git submodule foreach --recursive "git config --local --unset-all core.sshCommand"
        git submodule foreach --recursive "git config --local --unset-all http.https://github.com/.extraheader"
