name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:

    runs-on: windows-latest

    env:
      Nuitka_OPTIONS: "--onefile --standalone --include-module=gradio,json,requests --include-package=PIL.ImageQt --output-filename=app.exe app.py --assume-yes-for-downloads --show-progress --jobs=3"
      APP_BRANCH: "app"

    steps:
    - name: 创建python3.10
      uses: actions/checkout@v4
    - name: 启动环境
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 安装依赖
      run: |
        ping 127.0.0.1
    - name: 构建
      run: |
        ping 127.0.0.1
    - name: 发布
      id: rename-and-move
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
        $newFileName = "$timestamp_FAID.py"
        $originalFilePath = "app.py"
        $newFilePath = Join-Path -Path "." -ChildPath $newFileName
        $newFilePathInApps = Join-Path -Path "apps" -ChildPath $newFileName
        
        # 输出调试信息，确保变量正确生成
        Write-Output "Timestamp: $timestamp"
        Write-Output "New file name: $newFileName"
        Write-Output "Original file path: $originalFilePath"
        Write-Output "New file path: $newFilePath"
        Write-Output "New file path in apps: $newFilePathInApps"
        
        # 确保源文件存在
        if (Test-Path -Path $originalFilePath) {
            # 重命名文件
            Move-Item -Path $originalFilePath -Destination $newFilePath
            Write-Output "File has been renamed to: $newFilePath"
        
            # 确保目标目录存在，如果不存在则创建
            if (-Not (Test-Path -Path "apps")) {
                New-Item -ItemType Directory -Path "apps"
                Write-Output "Directory 'apps' has been created."
            }
        
            # 检查目标文件是否已存在，如果存在则删除
            if (Test-Path -Path $newFilePathInApps) {
                Remove-Item -Path $newFilePathInApps -Force
                Write-Output "Existing file $newFilePathInApps has been removed."
            }
        
            # 将文件移动到 apps/ 目录
            Move-Item -Path $newFilePath -Destination $newFilePathInApps
            Write-Output "File has been moved to: $newFilePathInApps"
        
            # 设置输出变量，假设这是在GitHub Actions中使用
            echo "::set-output name=newFileName::$newFileName"
        } else {
            Write-Output "Source file $originalFilePath does not exist."
        }
        
        # 配置 Git 并提交更改
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout main || git checkout -b main
        git add apps/$newFileName
        git commit -m "Add new build: $newFileName" || echo "No changes to commit"
        git push https://$ACTION_TOKEN@github.com/${{ github.repository }}.git main
