name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:

    runs-on: windows-latest

    env:
      Nuitka_OPTIONS: "--onefile --standalone --include-module=gradio,json,requests --include-package=PIL.ImageQt --output-filename=app.exe app.py --assume-yes-for-downloads --show-progress --jobs=3"
      APP_BRANCH: "app"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka
    - name: 构建
      run: |
        nuitka ${{ env.Nuitka_OPTIONS }}
    - name: 重命名
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
        $newFileName = "$timestamp_FAID.exe"
        $originalFilePath = "app.exe"
        $newFilePath = Join-Path (Split-Path $originalFilePath) $newFileName
        Move-Item -Path $originalFilePath -Destination $newFilePath
        Write-Output "File has been renamed to: $newFilePath"
    
